name: Update instances.json

on:
  push:
    branches: [ master ]

  workflow_dispatch: # run on manual trigger

  schedule:
    - cron: "0 */12 * * *" # run every 12 hours

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      INPUT_FILE: instances.txt
      OUTPUT_FILE: instances.json

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Generate instances
      run: |
       ./generate-instances-json.sh -i ${{env.INPUT_FILE}} -o ${{env.OUTPUT_FILE}}

    - name: Commit updated file back to the repository
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${{env.OUTPUT_FILE}} 
          git diff-index --quiet HEAD \
            && echo "No changes to commit" \
            || git commit -m "[update] Uupdate instances"
          git fetch
          git push
